# Generated by Django 3.0.2 on 2020-02-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_coupon_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(default='', max_length=120, unique=True)),
                ('charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
