# Generated by Django 3.0.2 on 2020-02-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20200205_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_name',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
    ]
