# Generated by Django 3.0.2 on 2020-02-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cart_coupon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon_name',
        ),
    ]
