# Generated by Django 3.0.2 on 2020-02-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax_total',
            new_name='delivery_charge',
        ),
    ]
