# Generated by Django 3.0.2 on 2020-02-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Started', 'Started'), ('Confirmed', 'Confirmed'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], default='Cash in delivery', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Confirmed', 'Confirmed'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], default='Started', max_length=120),
        ),
    ]
