# Generated by Django 3.0.2 on 2020-02-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200202_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash in delivery', 'Cash in delivery'), ('Bkash', 'Bkash'), ('Rocket', 'Rocket')], default='Cash in delivery', max_length=120),
        ),
    ]
