# Generated by Django 3.0.2 on 2020-02-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200206_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_count',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
