# Generated by Django 3.0.2 on 2020-02-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(default='', max_length=120),
        ),
    ]
