# Generated by Django 3.0.2 on 2020-02-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200206_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default='', max_length=120),
        ),
    ]
