# Generated by Django 3.0.2 on 2020-02-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200210_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Bkash', 'Bkash'), ('Rocket', 'Rocket')], default='Cash in delivery', max_length=120),
        ),
    ]
