# Generated by Django 3.0.2 on 2020-02-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200210_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone_no',
            field=models.CharField(default='', max_length=120),
        ),
    ]
